import argparse
import sys
import numpy as np
from collections import OrderedDict

parser = argparse.ArgumentParser()
parser.add_argument(
    '-m', 
    '--in_matrix', 
    required=True
    )
parser.add_argument(
    '-a', 
    '--assembly', 
    required=True
    )
parser.add_argument(
    '-o', 
    '--output',
    required=True
    )
args = parser.parse_args()

class Sprite_matrix:
    
    def __init__(self, matrix_input=None, matrix=None):
        # Loads SPRITE matrix from tab-delimited text file
        # Can manually define matrix instead (should be numpy array)
        if matrix_input:
            self.matrix = []
            for line in open(matrix_input):
                self.matrix.append([float(x) for x in line.split()])
            self.matrix = np.array(self.matrix)
        elif isinstance(matrix, np.ndarray):
            self.matrix = matrix
        else:
            sys.exit("Must initialize Sprite_matrix with either a matrix or a file path to a text file with a matrix")
        
        self.size = self.matrix.shape[0] # Both dimensions should be the same
    
    def contacts_by_distance(self):
        # Returns dictionary with the average contact value for a given distance between x and y
        contacts_by_distance_counts = {dist:0 for dist in range(self.size)}
        contacts_by_distance_vals = {dist:0 for dist in range(self.size)}
        
        for x in range(self.size):
            for y in range(self.size):
                dist = abs(x-y)
                contacts_by_distance_counts[dist] += 1
                contacts_by_distance_vals[dist] += self.matrix[x][y]
        
        contacts_by_distance_avg = {dist:contacts_by_distance_vals[dist]/contacts_by_distance_counts[dist] for dist in contacts_by_distance_vals}
        return contacts_by_distance_avg
    
    def distance_normalize(self, contacts_by_distance):
        # Distance-normalizes matrix contacts by dividing each contact by the amount expected based on distance between x and y
        # Normalization dictionary is given as argument; can be run with a dictionary generated by averaging across chromosomes
        out_matrix = self.matrix.copy()
        
        for x in range(self.size):
            for y in range(self.size):
                dist = abs(x-y)
                if float(contacts_by_distance[dist]) == 0:
                    out_matrix[x][y] = 0
                else:
                    out_matrix[x][y] /= contacts_by_distance[dist]
        
        self.matrix = out_matrix

    def pearson_correlation_matrix(self, zero_threshold=0.8):
        # Calculates matrix of Pearson correlation coefficients
        # The value at i, j in the correlation matrix represents the Pearson correlation
        # between row i and column j in the original matrix
        
        # Initialize output with zeros
        n = self.matrix.shape[0]
        correlation_matrix = np.zeros((n, n))
        
        # Some rows in SPRITE matrices are mostly zeros since the corresponding genomic loci lack mappable DNA
        # These zeros artificially inflate correlation coefficients, so they are ideally ignored
        # Set zero_threshold to None to include zeros if desired
        
        # First generate array denoting rows/columns that are mostly zeros
        if zero_threshold:
            zero_threshold_n = n*zero_threshold
            mostly_zeros = np.sum(self.matrix == 0, axis=1) / self.matrix.shape[1] >= 0.8
        else:
            np.zeros(n, dtype=bool)
        
        for i in range(n):
            for j in range(n):
                # Do not attempt to compute correlation if one of the rows/columns is mostly zeros
                if mostly_zeros[i] or mostly_zeros[j]:
                    continue
                
                row = self.matrix[i, :]
                col = self.matrix[:, j]
                
                # Mask row and column to ignore values corresponding to rows/columns that are mostly zeros
                masked_row = row[~mostly_zeros]
                masked_col = col[~mostly_zeros]
                
                # Compute Pearson correlation between the row and the column
                correlation = np.corrcoef(masked_row, masked_col)[0, 1]
                correlation_matrix[i, j] = correlation
        
        self.matrix = correlation_matrix

class All_matrices:
    
    def __init__(self, assembly_name):
        for cls in Assembly.__subclasses__():
            if cls.assembly_name == assembly_name:
                self.assembly = cls()
    
    def load_matrices(self, all_paths=None, chr1_path=None):
        # Loads SPRITE matrices for each chromosome given list of paths or path to chr1
        # If specifying all_paths, the file paths must be in the same order as the chromosomes in chr_sizes
        # If giving path to chr1, assumes that the other paths are the same except with chr1 replaced with each chromosome,
        # e.g. paths are /path/matrices/chr1/chr1_final.txt, /path/matrices/chr2/chr2_final.txt, etc.
        if not (all_paths or chr1_path):
            sys.exit("Must specify list of paths or path to chromosome 1 to load SPRITE matrices")
        
        if chr1_path:
            all_paths = []
            for chr in self.assembly.chr_names:
                all_paths.append(chr1_path.replace('chr1', chr))
        
        if self.assembly.n_chr != len(all_paths):
            sys.exit("Number of matrices to load is not the same as expected based on assembly")
        
        # Load the matrices as Sprite_matrix objects
        self.matrices = {chr:None for chr in self.assembly.chr_names}
        
        for i in range(self.assembly.n_chr):
            self.matrices[self.assembly.chr_names[i]] = Sprite_matrix(matrix_input=all_paths[i])
    
    def average_contacts_by_distance(self):
        # Returns the average contact value at a given distance between x and y across all chromosomes
        if not hasattr(self, "matrices"):
            sys.exit("Must load matrices before finding average contacts by distance")
        
        all_vals = {}
        all_counts = {}
        for chr, m in self.matrices.items():
            current = m.contacts_by_distance()
            for dist, val in current.items():
                if dist not in all_vals:
                    all_vals[dist] = 0
                all_vals[dist] += val
                if dist not in all_counts:
                    all_counts[dist] = 0
                all_counts[dist] += 1
        
        all_avg = {dist:val/all_counts[dist] for dist, val in all_vals.items()}
        return all_avg
    
    def normalize_all(self):
        # Normalize all contacts by distance between x and y
        # Defaults to normalizing based on average contacts by distance across all chromosomes
        # Stores normalized matrices separately from original
        if not hasattr(self, "matrices"):
            sys.exit("Must load matrices before normalizing SPRITE matrices by distance")
        
        if not hasattr(self, "average_contacts_by_distance"):
            sys.exit("Must find average contacts by distance before normalizing SPRITE matrices by distance")
        
        norm_dict=self.average_contacts_by_distance()
        
        # Create copies of matrices to normalize
        self.norm_matrices = {chr:Sprite_matrix(matrix=m.matrix.copy()) for chr, m in self.matrices.items()}
        
        for chr, m in self.norm_matrices.items():
            m.distance_normalize(norm_dict)
    
    def pearson_all(self, d_norm=True):
        # Generate Pearson correlation matrices for all matrices
        # Usually run on distance-normalized matrices, but can be run on non-normalized
        
        # Create copies of matrices to normalize
        if d_norm:
            self.pearson_matrices = {chr:Sprite_matrix(matrix=m.matrix.copy()) for chr, m in self.norm_matrices.items()}
        else:
            self.pearson_matrices = {chr:Sprite_matrix(matrix=m.matrix.copy()) for chr, m in self.matrices.items()}
        
        for chr, m in self.pearson_matrices.items():
            m.pearson_correlation_matrix()

    def main(self, out_path, all_paths=None, chr1_path=None):
        if all_paths:
            self.load_matrices(self, all_paths=all_paths)
        elif chr1_path:
            self.load_matrices(self, chr1_path=chr1_path)
        else:
            sys.exit("Must specify path to matrices")
        
        self.average_contacts_by_distance()
        self.normalize_all()
        self.pearson_all()
        
        for chr, m in self.norm_matrices.items():
            write_matrix(m.matrix, f'{out_path}_{chr}_norm.txt')
        
        for chr, m in self.pearson_matrices.items():
            write_matrix(m.matrix, f'{out_path}_{chr}_pearson.txt')

class Assembly:
    
    def __init__(self, exclude_Y=True, exclude_M=True):
        if exclude_Y:
            self.chr_sizes = OrderedDict([(chr, size) for (chr, size) in self.chr_sizes.items() if chr not in ['chrY', 'CP086569.2']])
        if exclude_M:
            self.chr_sizes = OrderedDict([(chr, size) for (chr, size) in self.chr_sizes.items() if chr not in ['chrM']])
        self.chr_names = [chr for (chr, size) in self.chr_sizes.items()]
        #self.chr_weights = [size for (chr, size) in self.chr_sizes.items()]
        #self.size = size
        #self.resolution = resolution
        self.n_chr = len(self.chr_names)

class Hg19(Assembly):
    
    assembly_name = 'hg19'

    def __init__(self):
        self.chr_sizes = OrderedDict([
            ('chr1', 249250621),
            ('chr2', 243199373),
            ('chr3', 198022430),
            ('chr4', 191154276),
            ('chr5', 180915260),
            ('chr6', 171115067),
            ('chr7', 159138663),
            ('chr8', 146364022),
            ('chr9', 141213431),
            ('chr10', 135534747),
            ('chr11', 135006516),
            ('chr12', 133851895),
            ('chr13', 115169878),
            ('chr14', 107349540),
            ('chr15', 102531392),
            ('chr16', 90354753),
            ('chr17', 81195210),
            ('chr18', 78077248),
            ('chr19', 59128983),
            ('chr20', 63025520),
            ('chr21', 48129895),
            ('chr22', 51304566),
            ('chrX', 155270560),
            ('chrY', 59373566),
            ('chrM', 16571)])
        super(Hg19, self).__init__()

class Hg38(Assembly):
    
    assembly_name = 'hg38'

    def __init__(self):
        self.chr_sizes = OrderedDict([
            ('chr1', 248956422),
            ('chr2', 242193529),
            ('chr3', 198295559),
            ('chr4', 190214555),
            ('chr5', 181538259),
            ('chr6', 170805979),
            ('chr7', 159345973),
            ('chr8', 145138636),
            ('chr9', 138394717),
            ('chr10', 133797422),
            ('chr11', 135086622),
            ('chr12', 133275309),
            ('chr13', 114364328),
            ('chr14', 107043718),
            ('chr15', 101991189),
            ('chr16', 90338345),
            ('chr17', 83257441),
            ('chr18', 80373285),
            ('chr19', 58617616),
            ('chr20', 64444167),
            ('chr21', 46709983),
            ('chr22', 50818468),
            ('chrX', 156040895),
            ('chrY', 57227415),
            ('chrM', 16569)])
        super(Hg38, self).__init__()

class T2T_CHM13v2_0(Assembly):
    
    assembly_name = 't2t_chm13'

    def __init__(self):
        self.chr_sizes = OrderedDict([
            ('NC_060925.1', 248387328),
            ('NC_060926.1', 242696752),
            ('NC_060927.1', 201105948),
            ('NC_060928.1', 193574945),
            ('NC_060929.1', 182045439),
            ('NC_060930.1', 172126628),
            ('NC_060931.1', 160567428),
            ('NC_060932.1', 146259331),
            ('NC_060933.1', 150617247),
            ('NC_060934.1', 134758134),
            ('NC_060935.1', 135127769),
            ('NC_060936.1', 133324548),
            ('NC_060937.1', 113566686),
            ('NC_060938.1', 101161492),
            ('NC_060939.1', 99753195),
            ('NC_060940.1', 96330374),
            ('NC_060941.1', 84276897),
            ('NC_060942.1', 80542538),
            ('NC_060943.1', 61707364),
            ('NC_060944.1', 66210255),
            ('NC_060945.1', 45090682),
            ('NC_060946.1', 51324926),
            ('NC_060947.1', 154259566),
            ('NC_060948.1', 62460029)])
        super(T2T_CHM13v2_0, self).__init__()

def write_matrix(matrix, out_path):
    # Writes a 2-dimensional numpy array as a tab-delimited text file
    output = matrix.tolist()
    output = ['\t'.join([str(x) for x in row]) for row in output]
    output = '\n'.join(output)
    with open(out_path, "x") as out_file:
        out_file.write(output)

all_matrices = All_matrices(args.assembly)
all_matrices.main(args.output, chr1_path=args.in_matrix)
